// SOFA1 ADMIN — cấu hình menu quản trị & dữ liệu mẫu cho từng màn hình
// ----------------------------------------------------------------------

export type Sofa1AdminSection = {
  slug: string;
  name: string;
  desc: string;
  kpis: { label: string; value: string; note?: string }[];
  columns: string[];
  rows: (string | number)[][];
};

export type Sofa1AdminGroup = {
  slug: string;
  name: string;
  icon: string;
  desc: string;
  sections: Sofa1AdminSection[];
};

const s = (
  slug: string,
  name: string,
  desc: string,
  kpis: [string, string, string?][],
  columns: string[],
  rows: (string | number)[][]
): Sofa1AdminSection => ({
  slug,
  name,
  desc,
  kpis: kpis.map(([label, value, note]) => ({ label, value, note })),
  columns,
  rows,
});

const STATUS = ['Đang hoạt động', 'Bản nháp', 'Chờ duyệt', 'Tạm ẩn'];

const page = (title: string, path: string, i: number): (string | number)[] => [
  title,
  path,
  STATUS[i % STATUS.length],
  `${12 + i * 3}/08/2026`,
  'Admin',
];

export const SOFA1_ADMIN_GROUPS: Sofa1AdminGroup[] = [
  {
    slug: 'cms',
    name: 'CMS',
    icon: 'solar:documents-bold-duotone',
    desc: 'Quản trị nội dung toàn bộ website: trang, menu, banner, slider và SEO trang tĩnh.',
    sections: [
      s('home', 'Trang chủ', 'Bố cục và các khối nội dung trang chủ.',
        [['Khối nội dung', '12'], ['Đang hiển thị', '10'], ['Lượt xem/tháng', '48.520']],
        ['Khối', 'Vị trí', 'Trạng thái', 'Cập nhật', 'Người sửa'],
        ['Hero Slider', 'Hero banner', 'Bộ sưu tập nổi bật', 'Sản phẩm bán chạy', 'Dự án tiêu biểu', 'Đánh giá khách hàng', 'Blog mới nhất', 'Đăng ký nhận tin']
          .map((t, i) => [t, `Section ${i + 1}`, STATUS[i % STATUS.length], `${5 + i}/08/2026`, 'Admin'])),
      s('about', 'Trang giới thiệu', 'Nội dung câu chuyện thương hiệu, xưởng sản xuất, đội ngũ.',
        [['Trang con', '6'], ['Đang hiển thị', '6'], ['Lượt xem/tháng', '9.140']],
        ['Trang', 'Đường dẫn', 'Trạng thái', 'Cập nhật', 'Người sửa'],
        [['Câu chuyện thương hiệu', '/sofa1/about'], ['Lịch sử phát triển', '/sofa1/about/history'],
         ['Xưởng sản xuất', '/sofa1/about/workshop'], ['Công nghệ', '/sofa1/about/technology'],
         ['Đội ngũ', '/sofa1/about/team'], ['Chứng nhận', '/sofa1/about/certificates']]
          .map(([t, p], i) => page(t, p, i))),
      s('contact', 'Trang liên hệ', 'Thông tin liên hệ, bản đồ, biểu mẫu.',
        [['Biểu mẫu', '3'], ['Yêu cầu mới', '27'], ['Thời gian phản hồi', '1,8 giờ']],
        ['Mục', 'Đường dẫn', 'Trạng thái', 'Cập nhật', 'Người sửa'],
        [['Form liên hệ', '/sofa1/contact'], ['Bản đồ showroom', '/sofa1/contact#map'],
         ['Hotline & email', '/sofa1/contact#info'], ['Đặt lịch tư vấn', '/sofa1/showrooms/consult']]
          .map(([t, p], i) => page(t, p, i))),
      s('policy', 'Trang chính sách', 'Bảo hành, đổi trả, vận chuyển, thanh toán, bảo mật.',
        [['Chính sách', '6'], ['Đã công bố', '5'], ['Chờ duyệt', '1']],
        ['Chính sách', 'Đường dẫn', 'Trạng thái', 'Cập nhật', 'Người sửa'],
        [['Chính sách bảo hành', '/sofa1/policy/warranty'], ['Chính sách đổi trả', '/sofa1/policy/return'],
         ['Chính sách vận chuyển', '/sofa1/policy/shipping'], ['Chính sách thanh toán', '/sofa1/policy/payment'],
         ['Chính sách bảo mật', '/sofa1/policy/privacy'], ['Chính sách đại lý', '/sofa1/b2b/policy']]
          .map(([t, p], i) => page(t, p, i))),
      s('terms', 'Trang điều khoản', 'Điều khoản sử dụng, mua bán, thành viên.',
        [['Văn bản', '4'], ['Phiên bản mới nhất', 'v3.2'], ['Hiệu lực', '01/08/2026']],
        ['Điều khoản', 'Đường dẫn', 'Trạng thái', 'Cập nhật', 'Người sửa'],
        [['Điều khoản sử dụng', '/sofa1/policy/terms'], ['Điều khoản mua bán', '/sofa1/policy/purchase'],
         ['Điều khoản thành viên', '/sofa1/policy/member'], ['Thoả thuận đại lý', '/sofa1/policy/dealer']]
          .map(([t, p], i) => page(t, p, i))),
      s('faq', 'Trang FAQ', 'Câu hỏi thường gặp theo nhóm chủ đề.',
        [['Câu hỏi', '38'], ['Nhóm chủ đề', '6'], ['Hữu ích', '92%']],
        ['Câu hỏi', 'Nhóm', 'Trạng thái', 'Cập nhật', 'Lượt xem'],
        [['Da bò thật khác da công nghiệp?', 'Chất liệu', 1420], ['Có thể đổi trả không?', 'Đổi trả', 980],
         ['Bảo hành gồm những gì?', 'Bảo hành', 1310], ['Giao hàng bao lâu?', 'Vận chuyển', 2050],
         ['Có trả góp không?', 'Thanh toán', 1730], ['Đặt đóng theo yêu cầu?', 'Sản phẩm', 860]]
          .map(([q, g, v], i) => [q, g, STATUS[i % 2], `${9 + i}/08/2026`, v])),
      s('blog', 'Trang blog', 'Bài viết, chuyên mục, tác giả và lịch xuất bản.',
        [['Bài viết', '124'], ['Chuyên mục', '8'], ['Bài chờ duyệt', '5']],
        ['Tiêu đề', 'Chuyên mục', 'Trạng thái', 'Xuất bản', 'Lượt đọc'],
        [['Chọn sofa cho phòng khách nhỏ', 'Tư vấn', 4120], ['Bảo quản sofa da đúng cách', 'Chăm sóc', 3380],
         ['Xu hướng nội thất 2026', 'Xu hướng', 5210], ['Phối màu sofa với tường', 'Thiết kế', 2760],
         ['Sofa vải hay sofa da?', 'Tư vấn', 6180], ['Quy trình đóng sofa thủ công', 'Hậu trường', 1940]]
          .map(([t, c, v], i) => [t, c, STATUS[i % 3], `${3 + i}/08/2026`, v])),
      s('menu', 'Menu', 'Cấu trúc menu chính, menu chân trang và menu di động.',
        [['Menu', '4'], ['Mục menu', '58'], ['Cấp sâu nhất', '3']],
        ['Menu', 'Vị trí', 'Số mục', 'Trạng thái', 'Cập nhật'],
        [['Menu chính', 'Header', 24], ['Menu chân trang', 'Footer', 18],
         ['Menu di động', 'Mobile', 22], ['Menu tài khoản', 'User', 9]]
          .map(([n, p, c], i) => [n, p, c, STATUS[i % 2], `${11 + i}/08/2026`])),
      s('banner', 'Banner', 'Banner quảng cáo theo vị trí và thời gian hiển thị.',
        [['Banner', '16'], ['Đang chạy', '9'], ['CTR trung bình', '3,4%']],
        ['Banner', 'Vị trí', 'Thời gian', 'Trạng thái', 'CTR'],
        [['Ưu đãi tháng 8', 'Top bar'], ['Sofa da nhập khẩu', 'Sidebar'], ['Miễn phí giao lắp', 'Giữa trang'],
         ['Bộ sưu tập Milano', 'Trang sản phẩm'], ['Đại lý toàn quốc', 'Footer']]
          .map(([n, p], i) => [n, p, `01/08 - ${20 + i}/09`, STATUS[i % 2], `${(2.4 + i * 0.4).toFixed(1)}%`])),
      s('slider', 'Slider', 'Slider trang chủ và trang danh mục.',
        [['Slider', '5'], ['Slide', '21'], ['Tự động chuyển', '6 giây']],
        ['Slider', 'Số slide', 'Trang áp dụng', 'Trạng thái', 'Cập nhật'],
        [['Hero trang chủ', 5, 'Trang chủ'], ['Bộ sưu tập', 4, 'Collections'],
         ['Dự án tiêu biểu', 6, 'Projects'], ['Showroom', 3, 'Showrooms'], ['Khuyến mãi', 3, 'Promotions']]
          .map(([n, c, p], i) => [n, c, p, STATUS[i % 2], `${7 + i}/08/2026`])),
      s('seo', 'SEO', 'Thẻ tiêu đề, mô tả, OG cho các trang nội dung.',
        [['Trang đã tối ưu', '86%'], ['Thiếu meta', '14'], ['Điểm SEO', '91/100']],
        ['Trang', 'Title', 'Độ dài mô tả', 'Trạng thái', 'Điểm'],
        [['Trang chủ', 'Sofa thủ công cao cấp | Sofa1', 152], ['Sản phẩm', 'Sofa da & vải nhập khẩu', 148],
         ['Bộ sưu tập', 'Bộ sưu tập sofa Milano', 139], ['Blog', 'Kiến thức nội thất', 126],
         ['Liên hệ', 'Liên hệ showroom Sofa1', 118]]
          .map(([p, t, l], i) => [p, t, `${l} ký tự`, i === 4 ? 'Cần tối ưu' : 'Tốt', 88 + i])),
      s('static', 'Trang tĩnh', 'Các trang landing và trang nội dung độc lập.',
        [['Trang tĩnh', '11'], ['Đang hiển thị', '9'], ['Bản nháp', '2']],
        ['Trang', 'Đường dẫn', 'Trạng thái', 'Cập nhật', 'Người sửa'],
        [['Hướng dẫn mua hàng', '/sofa1/support'], ['Tra cứu đơn hàng', '/sofa1/orders/tracking'],
         ['Thanh toán', '/sofa1/payment'], ['Tuyển dụng', '/sofa1/careers'], ['Khuyến mãi', '/sofa1/promotions']]
          .map(([t, p], i) => page(t, p, i))),
    ],
  },
  {
    slug: 'products',
    name: 'Sản phẩm',
    icon: 'solar:box-bold-duotone',
    desc: 'Quản lý danh mục, sản phẩm, thuộc tính, biến thể, tồn kho và giá bán.',
    sections: [
      s('categories', 'Danh mục', 'Cây danh mục sản phẩm nhiều cấp.',
        [['Danh mục', '24'], ['Danh mục cha', '6'], ['Sản phẩm chưa gán', '3']],
        ['Danh mục', 'Danh mục cha', 'Số sản phẩm', 'Trạng thái', 'Thứ tự'],
        [['Sofa da', '—', 48], ['Sofa vải', '—', 62], ['Sofa góc', 'Sofa vải', 31],
         ['Sofa băng', 'Sofa vải', 24], ['Ghế thư giãn', '—', 18], ['Bàn trà', '—', 26]]
          .map(([n, p, c], i) => [n, p, c, STATUS[i % 2], i + 1])),
      s('products', 'Sản phẩm', 'Danh sách sản phẩm, ảnh, mô tả và trạng thái bán.',
        [['Sản phẩm', '186'], ['Đang bán', '164'], ['Hết hàng', '9']],
        ['Mã', 'Tên sản phẩm', 'Danh mục', 'Giá bán', 'Trạng thái'],
        [['SF-1001', 'Sofa da Milano 3 chỗ', 'Sofa da', '42.900.000đ'],
         ['SF-1002', 'Sofa góc Verona L', 'Sofa góc', '36.500.000đ'],
         ['SF-1003', 'Sofa băng Torino', 'Sofa băng', '18.900.000đ'],
         ['SF-1004', 'Ghế thư giãn Firenze', 'Ghế thư giãn', '12.400.000đ'],
         ['SF-1005', 'Sofa vải Como 2 chỗ', 'Sofa vải', '15.800.000đ'],
         ['SF-1006', 'Bàn trà Roma', 'Bàn trà', '6.200.000đ']]
          .map(([c, n, cat, p], i) => [c, n, cat, p, i === 5 ? 'Hết hàng' : 'Đang bán'])),
      s('attributes', 'Thuộc tính', 'Chất liệu, màu sắc, kích thước, kiểu dáng.',
        [['Thuộc tính', '14'], ['Giá trị', '96'], ['Dùng cho lọc', '8']],
        ['Thuộc tính', 'Kiểu', 'Số giá trị', 'Dùng lọc', 'Trạng thái'],
        [['Chất liệu', 'Chọn 1', 8], ['Màu sắc', 'Bảng màu', 24], ['Kích thước', 'Chọn 1', 12],
         ['Số chỗ ngồi', 'Chọn 1', 6], ['Kiểu chân', 'Chọn 1', 5], ['Độ cứng đệm', 'Thanh trượt', 4]]
          .map(([n, t, c], i) => [n, t, c, i < 4 ? 'Có' : 'Không', STATUS[i % 2]])),
      s('variants', 'Biến thể sản phẩm', 'Tổ hợp biến thể theo SKU.',
        [['Biến thể', '742'], ['SKU hoạt động', '681'], ['Thiếu ảnh', '12']],
        ['SKU', 'Sản phẩm', 'Biến thể', 'Tồn kho', 'Giá'],
        [['SF-1001-BRN-3S', 'Sofa da Milano', 'Nâu / 3 chỗ', 12, '42.900.000đ'],
         ['SF-1001-BLK-3S', 'Sofa da Milano', 'Đen / 3 chỗ', 8, '42.900.000đ'],
         ['SF-1002-GRY-L', 'Sofa góc Verona', 'Xám / Góc trái', 5, '36.500.000đ'],
         ['SF-1003-BEI-B', 'Sofa băng Torino', 'Be / Băng dài', 0, '18.900.000đ'],
         ['SF-1005-GRN-2S', 'Sofa vải Como', 'Xanh rêu / 2 chỗ', 17, '15.800.000đ']])),
      s('inventory', 'Kho hàng', 'Tồn kho theo sản phẩm và kho.',
        [['SKU tồn', '681'], ['Sắp hết', '23'], ['Giá trị tồn', '18,4 tỷ']],
        ['SKU', 'Sản phẩm', 'Kho', 'Tồn', 'Ngưỡng cảnh báo'],
        [['SF-1001-BRN-3S', 'Sofa da Milano', 'Kho Hà Nội', 12, 5],
         ['SF-1002-GRY-L', 'Sofa góc Verona', 'Kho HCM', 5, 5],
         ['SF-1003-BEI-B', 'Sofa băng Torino', 'Kho Đà Nẵng', 0, 3],
         ['SF-1005-GRN-2S', 'Sofa vải Como', 'Kho Hà Nội', 17, 6],
         ['SF-1006-OAK', 'Bàn trà Roma', 'Kho HCM', 2, 4]])),
      s('pricing', 'Giá bán', 'Bảng giá, giá khuyến mãi và giá đại lý.',
        [['Bảng giá', '4'], ['Đang khuyến mãi', '32 SP'], ['Biên lợi nhuận TB', '38%']],
        ['Sản phẩm', 'Giá niêm yết', 'Giá khuyến mãi', 'Giá đại lý', 'Hiệu lực'],
        [['Sofa da Milano 3 chỗ', '42.900.000đ', '38.610.000đ', '33.200.000đ'],
         ['Sofa góc Verona L', '36.500.000đ', '34.675.000đ', '28.400.000đ'],
         ['Sofa băng Torino', '18.900.000đ', '—', '14.900.000đ'],
         ['Sofa vải Como 2 chỗ', '15.800.000đ', '14.220.000đ', '12.100.000đ'],
         ['Bàn trà Roma', '6.200.000đ', '—', '4.800.000đ']]
          .map((r, i) => [...r, `01/08 - ${25 + i}/09/2026`])),
    ],
  },
  {
    slug: 'warehouse',
    name: 'Kho hàng',
    icon: 'solar:box-minimalistic-bold-duotone',
    desc: 'Quản lý kho, nhập xuất, kiểm kê và điều chuyển hàng hoá.',
    sections: [
      s('overview', 'Tổng quan kho', 'Tình trạng tồn kho theo từng kho.',
        [['Kho', '4'], ['SKU', '681'], ['Giá trị tồn', '18,4 tỷ'], ['Sắp hết', '23']],
        ['Kho', 'Địa điểm', 'SKU', 'Tồn', 'Sức chứa'],
        [['Kho Hà Nội', 'Long Biên, Hà Nội', 248, 1420, '78%'],
         ['Kho HCM', 'Thủ Đức, TP.HCM', 262, 1610, '84%'],
         ['Kho Đà Nẵng', 'Liên Chiểu, Đà Nẵng', 96, 480, '52%'],
         ['Kho xưởng', 'Hà Nam', 75, 320, '41%']])),
      s('receipts', 'Nhập kho', 'Phiếu nhập từ xưởng và nhà cung cấp.',
        [['Phiếu tháng này', '38'], ['Chờ duyệt', '4'], ['Giá trị nhập', '3,2 tỷ']],
        ['Mã phiếu', 'Nguồn', 'Số lượng', 'Ngày', 'Trạng thái'],
        [['PN-2608-01', 'Xưởng Hà Nam', 84], ['PN-2608-02', 'NCC Da Italia', 120],
         ['PN-2608-03', 'NCC Khung gỗ', 60], ['PN-2608-04', 'Xưởng Hà Nam', 45]]
          .map(([m, n, q], i) => [m, n, q, `${10 + i}/08/2026`, i === 3 ? 'Chờ duyệt' : 'Hoàn tất'])),
      s('issues', 'Xuất kho', 'Phiếu xuất giao khách và điều chuyển.',
        [['Phiếu tháng này', '146'], ['Đang giao', '22'], ['Giá trị xuất', '5,8 tỷ']],
        ['Mã phiếu', 'Đích đến', 'Số lượng', 'Ngày', 'Trạng thái'],
        [['PX-2608-11', 'Đơn #10238', 1], ['PX-2608-12', 'Đại lý Hải Phòng', 12],
         ['PX-2608-13', 'Showroom Cầu Giấy', 6], ['PX-2608-14', 'Đơn #10244', 2]]
          .map(([m, n, q], i) => [m, n, q, `${12 + i}/08/2026`, i % 2 ? 'Đang giao' : 'Hoàn tất'])),
      s('stocktake', 'Kiểm kê', 'Đợt kiểm kê định kỳ và chênh lệch.',
        [['Đợt kiểm kê', '6/năm'], ['Chênh lệch', '0,4%'], ['Gần nhất', '31/07/2026']],
        ['Đợt', 'Kho', 'SKU kiểm', 'Chênh lệch', 'Trạng thái'],
        [['KK-2607', 'Kho Hà Nội', 248, '-3'], ['KK-2607', 'Kho HCM', 262, '+1'],
         ['KK-2607', 'Kho Đà Nẵng', 96, '0'], ['KK-2608', 'Kho xưởng', 75, 'Đang kiểm']]
          .map((r, i) => [...r, i === 3 ? 'Đang thực hiện' : 'Hoàn tất'])),
      s('transfers', 'Điều chuyển', 'Điều chuyển hàng giữa các kho và showroom.',
        [['Lệnh tháng này', '14'], ['Đang vận chuyển', '3'], ['Thời gian TB', '2,1 ngày']],
        ['Mã lệnh', 'Từ kho', 'Đến kho', 'Số lượng', 'Trạng thái'],
        [['DC-2608-01', 'Kho HCM', 'Kho Đà Nẵng', 18], ['DC-2608-02', 'Kho Hà Nội', 'Showroom Cầu Giấy', 6],
         ['DC-2608-03', 'Kho xưởng', 'Kho Hà Nội', 32]]
          .map((r, i) => [...r, i === 2 ? 'Đang vận chuyển' : 'Hoàn tất'])),
    ],
  },
  {
    slug: 'orders',
    name: 'Đơn hàng',
    icon: 'solar:cart-large-2-bold-duotone',
    desc: 'Xử lý đơn hàng, thanh toán, vận chuyển, hoàn tiền và đổi trả.',
    sections: [
      s('orders', 'Đơn hàng', 'Danh sách đơn hàng theo trạng thái xử lý.',
        [['Đơn tháng này', '412'], ['Chờ xử lý', '28'], ['Doanh thu', '6,4 tỷ'], ['Giá trị TB', '15,6 triệu']],
        ['Mã đơn', 'Khách hàng', 'Sản phẩm', 'Tổng tiền', 'Trạng thái'],
        [['#10238', 'Nguyễn Minh Anh', 'Sofa da Milano 3 chỗ', '42.900.000đ', 'Đang sản xuất'],
         ['#10239', 'Trần Quốc Bảo', 'Sofa góc Verona L', '36.500.000đ', 'Chờ xác nhận'],
         ['#10240', 'Lê Thu Hà', 'Sofa băng Torino x2', '37.800.000đ', 'Đang giao'],
         ['#10241', 'Phạm Văn Dũng', 'Ghế thư giãn Firenze', '12.400.000đ', 'Hoàn tất'],
         ['#10242', 'Đỗ Khánh Linh', 'Sofa vải Como 2 chỗ', '15.800.000đ', 'Hoàn tất'],
         ['#10243', 'Vũ Hoàng Nam', 'Bàn trà Roma x3', '18.600.000đ', 'Đã huỷ']]),
      s('payments', 'Thanh toán', 'Giao dịch thanh toán và đối soát.',
        [['Giao dịch', '389'], ['Thành công', '96,4%'], ['Chờ đối soát', '11']],
        ['Mã GD', 'Đơn hàng', 'Phương thức', 'Số tiền', 'Trạng thái'],
        [['TT-88231', '#10238', 'Chuyển khoản', '42.900.000đ', 'Thành công'],
         ['TT-88232', '#10239', 'Trả góp 0%', '36.500.000đ', 'Chờ duyệt'],
         ['TT-88233', '#10240', 'COD', '37.800.000đ', 'Chờ thu'],
         ['TT-88234', '#10241', 'Thẻ tín dụng', '12.400.000đ', 'Thành công'],
         ['TT-88235', '#10243', 'Ví điện tử', '18.600.000đ', 'Đã hoàn']]),
      s('shipping', 'Vận chuyển', 'Đơn vận, lịch giao lắp và trạng thái giao hàng.',
        [['Đơn vận', '198'], ['Đang giao', '34'], ['Giao đúng hẹn', '97,1%']],
        ['Mã vận đơn', 'Đơn hàng', 'Đơn vị', 'Lịch giao', 'Trạng thái'],
        [['VD-5521', '#10240', 'Đội giao lắp nội bộ', '18/08/2026', 'Đang giao'],
         ['VD-5522', '#10238', 'Đội giao lắp nội bộ', '26/08/2026', 'Chờ xuất kho'],
         ['VD-5523', '#10241', 'GHTK Cồng kềnh', '14/08/2026', 'Đã giao'],
         ['VD-5524', '#10242', 'Viettel Post', '13/08/2026', 'Đã giao']]),
      s('refunds', 'Hoàn tiền', 'Yêu cầu hoàn tiền và tiến độ xử lý.',
        [['Yêu cầu', '9'], ['Đã hoàn', '6'], ['Giá trị hoàn', '84,2 triệu']],
        ['Mã', 'Đơn hàng', 'Lý do', 'Số tiền', 'Trạng thái'],
        [['HT-201', '#10243', 'Khách huỷ đơn', '18.600.000đ', 'Đã hoàn'],
         ['HT-202', '#10199', 'Giao chậm', '5.000.000đ', 'Đang xử lý'],
         ['HT-203', '#10187', 'Lỗi sản xuất', '15.800.000đ', 'Đã hoàn'],
         ['HT-204', '#10221', 'Sai màu đặt', '12.400.000đ', 'Chờ duyệt']]),
      s('returns', 'Đổi trả', 'Phiếu đổi trả trong 30 ngày và bảo hành.',
        [['Phiếu đổi trả', '14'], ['Tỷ lệ đổi trả', '1,2%'], ['Xử lý TB', '3,4 ngày']],
        ['Mã', 'Đơn hàng', 'Sản phẩm', 'Hình thức', 'Trạng thái'],
        [['DT-118', '#10187', 'Sofa vải Como', 'Đổi sản phẩm', 'Hoàn tất'],
         ['DT-119', '#10221', 'Ghế thư giãn Firenze', 'Đổi màu', 'Đang xử lý'],
         ['DT-120', '#10205', 'Bàn trà Roma', 'Trả hàng', 'Chờ nhận hàng'],
         ['DT-121', '#10193', 'Sofa băng Torino', 'Bảo hành', 'Đang sửa chữa']]),
    ],
  },
  {
    slug: 'crm',
    name: 'CRM',
    icon: 'solar:users-group-rounded-bold-duotone',
    desc: 'Khách hàng, leads, lịch sử mua hàng và chăm sóc sau bán.',
    sections: [
      s('customers', 'Khách hàng', 'Hồ sơ khách hàng và phân nhóm.',
        [['Khách hàng', '4.286'], ['Khách VIP', '184'], ['Mua lại', '31%']],
        ['Khách hàng', 'Điện thoại', 'Nhóm', 'Số đơn', 'Tổng chi tiêu'],
        [['Nguyễn Minh Anh', '0912 xxx 481', 'VIP', 6, '182.400.000đ'],
         ['Trần Quốc Bảo', '0987 xxx 220', 'Thân thiết', 3, '78.200.000đ'],
         ['Lê Thu Hà', '0903 xxx 117', 'Mới', 1, '37.800.000đ'],
         ['Phạm Văn Dũng', '0938 xxx 654', 'Thân thiết', 4, '96.100.000đ'],
         ['Đỗ Khánh Linh', '0911 xxx 903', 'Mới', 1, '15.800.000đ']]),
      s('leads', 'Leads', 'Khách tiềm năng theo nguồn và giai đoạn.',
        [['Leads tháng', '638'], ['Đang chăm sóc', '212'], ['Tỷ lệ chốt', '18,4%']],
        ['Lead', 'Nguồn', 'Nhu cầu', 'Giai đoạn', 'Phụ trách'],
        [['Hoàng Anh Tuấn', 'Facebook Ads', 'Sofa góc phòng khách', 'Tư vấn', 'Ngọc Anh'],
         ['Mai Phương', 'Google Ads', 'Sofa da 3 chỗ', 'Báo giá', 'Hải Nam'],
         ['Công ty TNHH Vạn Phát', 'Giới thiệu', 'Nội thất văn phòng', 'Đàm phán', 'Thu Trang'],
         ['Nguyễn Đức Hải', 'Showroom', 'Ghế thư giãn', 'Mới', 'Ngọc Anh'],
         ['Trịnh Bảo Ngọc', 'Zalo OA', 'Sofa vải 2 chỗ', 'Tư vấn', 'Hải Nam']]),
      s('purchase-history', 'Lịch sử mua hàng', 'Toàn bộ giao dịch theo khách hàng.',
        [['Giao dịch', '9.412'], ['Giá trị TB', '15,6 triệu'], ['Chu kỳ mua lại', '14 tháng']],
        ['Khách hàng', 'Đơn hàng', 'Ngày mua', 'Giá trị', 'Kênh'],
        [['Nguyễn Minh Anh', '#10238', '12/08/2026', '42.900.000đ', 'Website'],
         ['Nguyễn Minh Anh', '#09871', '03/02/2026', '28.600.000đ', 'Showroom'],
         ['Phạm Văn Dũng', '#10241', '10/08/2026', '12.400.000đ', 'Website'],
         ['Trần Quốc Bảo', '#10239', '11/08/2026', '36.500.000đ', 'Hotline'],
         ['Lê Thu Hà', '#10240', '11/08/2026', '37.800.000đ', 'Website']]),
      s('care', 'Chăm sóc khách hàng', 'Ticket hỗ trợ, bảo trì và khảo sát hài lòng.',
        [['Ticket mở', '26'], ['Hài lòng', '4,8/5'], ['Phản hồi TB', '1,8 giờ']],
        ['Ticket', 'Khách hàng', 'Chủ đề', 'Mức ưu tiên', 'Trạng thái'],
        [['#TK-771', 'Lê Thu Hà', 'Hẹn lịch giao lắp', 'Trung bình', 'Đang xử lý'],
         ['#TK-772', 'Phạm Văn Dũng', 'Bảo trì đệm', 'Thấp', 'Đã lên lịch'],
         ['#TK-773', 'Nguyễn Minh Anh', 'Tư vấn phối màu', 'Thấp', 'Hoàn tất'],
         ['#TK-774', 'Đỗ Khánh Linh', 'Khiếu nại vết xước', 'Cao', 'Đang xử lý']]),
    ],
  },
  {
    slug: 'marketing',
    name: 'Marketing',
    icon: 'solar:megaphone-bold-duotone',
    desc: 'Chiến dịch email, SMS, push, mã giảm giá và affiliate.',
    sections: [
      s('email', 'Email Marketing', 'Chiến dịch email và tự động hoá.',
        [['Chiến dịch', '18'], ['Tỷ lệ mở', '38,2%'], ['Tỷ lệ click', '6,4%']],
        ['Chiến dịch', 'Tệp gửi', 'Đã gửi', 'Tỷ lệ mở', 'Trạng thái'],
        [['Ưu đãi tháng 8', 'Toàn bộ', 12400, '41,2%', 'Đã gửi'],
         ['Giỏ hàng bỏ quên', 'Tự động', 860, '52,7%', 'Đang chạy'],
         ['Ra mắt BST Milano', 'Khách VIP', 1840, '48,1%', 'Đã gửi'],
         ['Chăm sóc sau mua', 'Tự động', 640, '61,3%', 'Đang chạy'],
         ['Newsletter tuần', 'Đăng ký', 9800, '29,4%', 'Lên lịch']]),
      s('sms', 'SMS Marketing', 'Tin nhắn chăm sóc và khuyến mãi.',
        [['Tin đã gửi', '24.800'], ['Tỷ lệ nhận', '98,6%'], ['Chi phí/tin', '290đ']],
        ['Chiến dịch', 'Tệp gửi', 'Đã gửi', 'Tỷ lệ click', 'Trạng thái'],
        [['Flash sale cuối tuần', 'Khách cũ', 8200, '4,1%', 'Đã gửi'],
         ['Nhắc lịch giao lắp', 'Tự động', 412, '—', 'Đang chạy'],
         ['Sinh nhật khách hàng', 'Tự động', 186, '7,8%', 'Đang chạy'],
         ['Mời tham quan showroom', 'Lead', 3600, '3,2%', 'Đã gửi']]),
      s('push', 'Push Notification', 'Thông báo đẩy web và ứng dụng.',
        [['Người đăng ký', '18.240'], ['Tỷ lệ click', '5,7%'], ['Huỷ đăng ký', '1,2%']],
        ['Thông báo', 'Đối tượng', 'Đã gửi', 'Click', 'Trạng thái'],
        [['Giảm 10% sofa da', 'Tất cả', 18240, '6,2%', 'Đã gửi'],
         ['Hàng về kho', 'Quan tâm SP', 2400, '9,4%', 'Đã gửi'],
         ['Đơn hàng đang giao', 'Tự động', 340, '31,8%', 'Đang chạy'],
         ['Blog mới', 'Đọc blog', 5600, '3,1%', 'Lên lịch']]),
      s('coupon', 'Coupon', 'Mã giảm giá theo chiến dịch và điều kiện áp dụng.',
        [['Mã đang chạy', '12'], ['Lượt dùng', '1.284'], ['Doanh thu từ mã', '1,8 tỷ']],
        ['Mã', 'Ưu đãi', 'Điều kiện', 'Đã dùng', 'Hiệu lực'],
        [['SOFA10', 'Giảm 10%', 'Đơn từ 20 triệu', 412, '01/08 - 31/08'],
         ['FREESHIP', 'Miễn phí giao lắp', 'Nội thành', 286, '01/08 - 30/09'],
         ['NEW500', 'Giảm 500.000đ', 'Khách mới', 194, '01/07 - 31/12'],
         ['VIP15', 'Giảm 15%', 'Khách VIP', 88, '01/08 - 31/08'],
         ['B2B20', 'Giảm 20%', 'Đại lý', 304, 'Không giới hạn']]),
      s('affiliate', 'Affiliate', 'Cộng tác viên, hoa hồng và thanh toán.',
        [['Cộng tác viên', '146'], ['Đơn giới thiệu', '318'], ['Hoa hồng tháng', '184 triệu']],
        ['Cộng tác viên', 'Kênh', 'Đơn', 'Doanh thu', 'Hoa hồng'],
        [['Nội Thất Review', 'YouTube', 68, '1,2 tỷ', '60.000.000đ'],
         ['Home Decor VN', 'Facebook', 52, '860 triệu', '43.000.000đ'],
         ['Chị Hà Decor', 'TikTok', 44, '620 triệu', '31.000.000đ'],
         ['Blog Sống Đẹp', 'Website', 31, '410 triệu', '20.500.000đ']]),
    ],
  },
  {
    slug: 'analytics',
    name: 'Analytics',
    icon: 'solar:chart-square-bold-duotone',
    desc: 'Doanh thu, sản phẩm bán chạy, nguồn truy cập, hành vi và chuyển đổi.',
    sections: [
      s('revenue', 'Doanh thu', 'Doanh thu theo thời gian, kênh và khu vực.',
        [['Doanh thu tháng', '6,4 tỷ'], ['Tăng trưởng', '+18,2%'], ['Đơn hàng', '412'], ['AOV', '15,6 triệu']],
        ['Kênh', 'Doanh thu', 'Đơn hàng', 'AOV', 'Tăng trưởng'],
        [['Website', '3,1 tỷ', 198, '15,6 triệu', '+22%'],
         ['Showroom', '2,0 tỷ', 108, '18,5 triệu', '+11%'],
         ['Đại lý B2B', '980 triệu', 64, '15,3 triệu', '+26%'],
         ['Hotline', '320 triệu', 42, '7,6 triệu', '-4%']]),
      s('best-sellers', 'Sản phẩm bán chạy', 'Top sản phẩm theo doanh số và số lượng.',
        [['SKU bán chạy', '32'], ['Top 10 chiếm', '46% DT'], ['Tồn xoay vòng', '5,2 lần/năm']],
        ['Sản phẩm', 'Đã bán', 'Doanh thu', 'Tồn kho', 'Xu hướng'],
        [['Sofa da Milano 3 chỗ', 48, '2,05 tỷ', 12, '↑ 24%'],
         ['Sofa góc Verona L', 36, '1,31 tỷ', 5, '↑ 12%'],
         ['Sofa vải Como 2 chỗ', 62, '980 triệu', 17, '↑ 31%'],
         ['Sofa băng Torino', 28, '529 triệu', 0, '↓ 6%'],
         ['Ghế thư giãn Firenze', 41, '508 triệu', 9, '↑ 8%']]),
      s('traffic', 'Nguồn truy cập', 'Lưu lượng theo kênh và chiến dịch.',
        [['Phiên/tháng', '186.400'], ['Người dùng mới', '68%'], ['Thời gian TB', '3:12']],
        ['Nguồn', 'Phiên', 'Tỷ lệ', 'Thoát', 'Chuyển đổi'],
        [['Google Organic', 78400, '42,1%', '38%', '2,8%'],
         ['Google Ads', 41200, '22,1%', '46%', '3,4%'],
         ['Facebook', 32800, '17,6%', '52%', '1,9%'],
         ['Trực tiếp', 21600, '11,6%', '34%', '4,1%'],
         ['Giới thiệu', 12400, '6,6%', '41%', '2,2%']]),
      s('behavior', 'Hành vi khách hàng', 'Trang được xem, luồng di chuyển và tương tác.',
        [['Trang/phiên', '4,6'], ['Thêm giỏ hàng', '8,2%'], ['Xem 3D/AR', '12.400 lượt']],
        ['Trang', 'Lượt xem', 'Thời gian TB', 'Thoát', 'Thêm giỏ'],
        [['Trang chủ', 62400, '1:48', '28%', '—'],
         ['Danh sách sản phẩm', 48200, '3:24', '31%', '6,1%'],
         ['Chi tiết sản phẩm', 39800, '4:12', '26%', '14,8%'],
         ['Bộ sưu tập', 18600, '2:36', '38%', '4,2%'],
         ['Blog', 16400, '5:02', '62%', '0,4%']]),
      s('conversion', 'Tỷ lệ chuyển đổi', 'Phễu chuyển đổi từ truy cập đến đơn hàng.',
        [['Chuyển đổi', '2,9%'], ['Bỏ giỏ hàng', '64,2%'], ['Chuyển đổi showroom', '31,4%']],
        ['Bước phễu', 'Người dùng', 'Tỷ lệ giữ', 'Rời bỏ', 'Ghi chú'],
        [['Truy cập', 186400, '100%', '—', 'Tổng phiên'],
         ['Xem sản phẩm', 96200, '51,6%', '48,4%', 'Cần tối ưu danh mục'],
         ['Thêm giỏ hàng', 15280, '15,9%', '84,1%', 'Ưu đãi giao lắp'],
         ['Thanh toán', 8420, '55,1%', '44,9%', 'Rút gọn biểu mẫu'],
         ['Đặt hàng', 5410, '64,2%', '35,8%', 'Hỗ trợ trả góp']]),
    ],
  },
  {
    slug: 'seo',
    name: 'SEO',
    icon: 'solar:magnifer-bold-duotone',
    desc: 'Tối ưu SEO cho từng nhóm trang, sitemap, robots và schema.',
    sections: [
      s('category', 'Trang danh mục', 'Tối ưu tiêu đề, mô tả và nội dung danh mục.',
        [['Trang', '24'], ['Đã tối ưu', '21'], ['Từ khoá top 10', '86']],
        ['Danh mục', 'Từ khoá chính', 'Thứ hạng', 'Điểm SEO', 'Trạng thái'],
        [['Sofa da', 'sofa da cao cấp', 3, 94], ['Sofa vải', 'sofa vải đẹp', 6, 89],
         ['Sofa góc', 'sofa góc phòng khách', 4, 92], ['Sofa băng', 'sofa băng giá rẻ', 11, 78],
         ['Ghế thư giãn', 'ghế thư giãn nhập khẩu', 8, 84]]
          .map((r, i) => [...r, i === 3 ? 'Cần tối ưu' : 'Tốt'])),
      s('product', 'Trang sản phẩm', 'Meta, ảnh alt và schema sản phẩm.',
        [['Sản phẩm', '186'], ['Có schema', '178'], ['Thiếu alt ảnh', '22']],
        ['Sản phẩm', 'Từ khoá', 'Thứ hạng', 'Schema', 'Trạng thái'],
        [['Sofa da Milano 3 chỗ', 'sofa da milano', 2, 'Product + Review'],
         ['Sofa góc Verona L', 'sofa góc verona', 5, 'Product'],
         ['Sofa vải Como 2 chỗ', 'sofa vải 2 chỗ', 9, 'Product'],
         ['Sofa băng Torino', 'sofa băng torino', 7, 'Thiếu'],
         ['Ghế thư giãn Firenze', 'ghế thư giãn da', 12, 'Product']]
          .map((r, i) => [...r, i === 3 ? 'Cần bổ sung' : 'Tốt'])),
      s('collection', 'Trang bộ sưu tập', 'SEO cho landing bộ sưu tập.',
        [['Bộ sưu tập', '9'], ['Đã tối ưu', '8'], ['Traffic/tháng', '18.600']],
        ['Bộ sưu tập', 'Từ khoá', 'Truy cập', 'Điểm SEO', 'Trạng thái'],
        [['Milano', 'bộ sưu tập sofa milano', 6200, 93], ['Verona', 'sofa verona', 4100, 88],
         ['Como', 'sofa como', 3400, 85], ['Torino', 'sofa torino', 2600, 81],
         ['Firenze', 'ghế firenze', 2300, 76]]
          .map((r, i) => [...r, i === 4 ? 'Cần tối ưu' : 'Tốt'])),
      s('project', 'Trang dự án', 'SEO cho trang dự án thi công.',
        [['Dự án', '38'], ['Đã tối ưu', '31'], ['Truy cập', '9.200']],
        ['Dự án', 'Từ khoá', 'Truy cập', 'Điểm SEO', 'Trạng thái'],
        [['Penthouse Vinhomes', 'nội thất penthouse', 2400, 90],
         ['Villa Ecopark', 'nội thất villa', 1900, 87],
         ['Khách sạn Đà Nẵng', 'nội thất khách sạn', 1600, 82],
         ['Căn hộ Masteri', 'sofa căn hộ', 1500, 79],
         ['Văn phòng Keangnam', 'sofa văn phòng', 1200, 74]]
          .map((r, i) => [...r, i > 3 ? 'Cần tối ưu' : 'Tốt'])),
      s('showroom', 'Trang showroom', 'SEO local cho từng showroom.',
        [['Showroom', '6'], ['Google Business', '6'], ['Đánh giá TB', '4,8/5']],
        ['Showroom', 'Từ khoá địa phương', 'Thứ hạng', 'Đánh giá', 'Trạng thái'],
        [['Cầu Giấy, Hà Nội', 'showroom sofa cầu giấy', 1, '4,9/5'],
         ['Long Biên, Hà Nội', 'sofa long biên', 2, '4,8/5'],
         ['Quận 7, TP.HCM', 'showroom sofa quận 7', 3, '4,7/5'],
         ['Thủ Đức, TP.HCM', 'sofa thủ đức', 4, '4,8/5'],
         ['Hải Châu, Đà Nẵng', 'sofa đà nẵng', 2, '4,9/5']]
          .map((r) => [...r, 'Tốt'])),
      s('blog', 'Trang blog', 'SEO nội dung, internal link và từ khoá dài.',
        [['Bài viết', '124'], ['Từ khoá top 10', '212'], ['Traffic organic', '42.600']],
        ['Bài viết', 'Từ khoá', 'Thứ hạng', 'Truy cập', 'Trạng thái'],
        [['Chọn sofa cho phòng khách nhỏ', 'sofa phòng khách nhỏ', 2, 8400],
         ['Bảo quản sofa da đúng cách', 'bảo quản sofa da', 1, 6200],
         ['Xu hướng nội thất 2026', 'xu hướng nội thất 2026', 4, 5100],
         ['Sofa vải hay sofa da?', 'nên mua sofa vải hay da', 3, 7300],
         ['Phối màu sofa với tường', 'phối màu sofa', 9, 2600]]
          .map((r, i) => [...r, i === 4 ? 'Cần tối ưu' : 'Tốt'])),
      s('brand', 'Trang thương hiệu', 'Trang thương hiệu và entity SEO.',
        [['Trang thương hiệu', '5'], ['Backlink', '1.284'], ['Điểm uy tín', '46/100']],
        ['Thương hiệu', 'Đường dẫn', 'Backlink', 'Điểm SEO', 'Trạng thái'],
        [['Sofa1 Handcraft', '/sofa1/about', 620, 92], ['Milano Leather', '/sofa1/collections/milano', 240, 86],
         ['Como Fabric', '/sofa1/collections/como', 180, 82], ['Verona Design', '/sofa1/collections/verona', 152, 80],
         ['Torino Classic', '/sofa1/collections/torino', 92, 74]]
          .map((r, i) => [...r, i === 4 ? 'Cần tối ưu' : 'Tốt'])),
      s('sitemap', 'Sitemap', 'Sơ đồ trang XML gửi tới công cụ tìm kiếm.',
        [['URL', '486'], ['Đã lập chỉ mục', '452'], ['Lỗi', '4']],
        ['Sitemap', 'Số URL', 'Đã index', 'Cập nhật', 'Trạng thái'],
        [['sitemap-index.xml', 486, 452], ['sitemap-products.xml', 186, 179],
         ['sitemap-collections.xml', 9, 9], ['sitemap-blog.xml', 124, 118],
         ['sitemap-pages.xml', 42, 40]]
          .map((r, i) => [...r, `${13 + i}/08/2026`, i === 3 ? 'Có cảnh báo' : 'Tốt'])),
      s('robots', 'Robots', 'Quy tắc thu thập dữ liệu cho từng bot.',
        [['Quy tắc', '12'], ['Chặn', '5 đường dẫn'], ['Cập nhật', '10/08/2026']],
        ['User-agent', 'Quy tắc', 'Đường dẫn', 'Trạng thái', 'Cập nhật'],
        [['*', 'Allow', '/'], ['*', 'Disallow', '/sofa1/admin'], ['*', 'Disallow', '/sofa1/checkout'],
         ['*', 'Disallow', '/sofa1/account'], ['Googlebot', 'Allow', '/sofa1/products']]
          .map((r, i) => [...r, 'Đang áp dụng', `${10 + (i % 3)}/08/2026`])),
      s('schema', 'Schema', 'Dữ liệu có cấu trúc theo loại trang.',
        [['Loại schema', '8'], ['Trang có schema', '92%'], ['Lỗi kiểm tra', '3']],
        ['Loại schema', 'Áp dụng cho', 'Số trang', 'Lỗi', 'Trạng thái'],
        [['Organization', 'Toàn site', 1, 0], ['Product', 'Trang sản phẩm', 178, 2],
         ['BreadcrumbList', 'Toàn site', 486, 0], ['Article', 'Blog', 124, 1],
         ['LocalBusiness', 'Showroom', 6, 0], ['FAQPage', 'FAQ', 1, 0]]
          .map((r) => [...r, Number(r[3]) > 0 ? 'Cần sửa' : 'Tốt'])),
    ],
  },
  {
    slug: 'permissions',
    name: 'Phân quyền',
    icon: 'solar:shield-user-bold-duotone',
    desc: 'Người dùng hệ thống, vai trò, quyền hạn và nhật ký hoạt động.',
    sections: [
      s('users', 'Người dùng', 'Tài khoản quản trị và nhân sự.',
        [['Người dùng', '38'], ['Đang hoạt động', '34'], ['Bật 2FA', '29']],
        ['Người dùng', 'Email', 'Vai trò', '2FA', 'Trạng thái'],
        [['Nguyễn Ngọc Anh', 'ngocanh@sofa1.vn', 'Quản trị viên', 'Bật'],
         ['Trần Hải Nam', 'hainam@sofa1.vn', 'Quản lý bán hàng', 'Bật'],
         ['Lê Thu Trang', 'thutrang@sofa1.vn', 'Biên tập nội dung', 'Tắt'],
         ['Phạm Đức Long', 'duclong@sofa1.vn', 'Quản lý kho', 'Bật'],
         ['Vũ Mai Chi', 'maichi@sofa1.vn', 'Marketing', 'Bật']]
          .map((r, i) => [...r, i === 2 ? 'Tạm khoá' : 'Đang hoạt động'])),
      s('roles', 'Vai trò', 'Nhóm vai trò và phạm vi truy cập.',
        [['Vai trò', '7'], ['Vai trò tuỳ chỉnh', '3'], ['Người dùng/vai trò TB', '5,4']],
        ['Vai trò', 'Mô tả', 'Số người dùng', 'Số quyền', 'Trạng thái'],
        [['Quản trị viên', 'Toàn quyền hệ thống', 3, 64],
         ['Quản lý bán hàng', 'Đơn hàng, CRM, báo cáo', 8, 32],
         ['Biên tập nội dung', 'CMS, blog, SEO', 6, 24],
         ['Quản lý kho', 'Kho hàng, tồn kho', 5, 18],
         ['Marketing', 'Chiến dịch, coupon', 7, 21],
         ['Cộng tác viên', 'Xem báo cáo affiliate', 9, 6]]
          .map((r) => [...r, 'Đang hoạt động'])),
      s('permissions', 'Quyền hạn', 'Ma trận quyền theo module.',
        [['Quyền', '64'], ['Module', '9'], ['Quyền nhạy cảm', '11']],
        ['Module', 'Xem', 'Tạo', 'Sửa', 'Xoá'],
        [['CMS', 'Tất cả', 'Biên tập trở lên', 'Biên tập trở lên', 'Quản trị'],
         ['Sản phẩm', 'Tất cả', 'Quản lý', 'Quản lý', 'Quản trị'],
         ['Kho hàng', 'Quản lý kho', 'Quản lý kho', 'Quản lý kho', 'Quản trị'],
         ['Đơn hàng', 'Bán hàng', 'Bán hàng', 'Bán hàng', 'Quản trị'],
         ['CRM', 'Bán hàng', 'Bán hàng', 'Bán hàng', 'Quản trị'],
         ['Marketing', 'Marketing', 'Marketing', 'Marketing', 'Quản trị'],
         ['Analytics', 'Tất cả', '—', '—', '—'],
         ['SEO', 'Biên tập', 'Biên tập', 'Biên tập', 'Quản trị'],
         ['Phân quyền', 'Quản trị', 'Quản trị', 'Quản trị', 'Quản trị']]),
      s('logs', 'Nhật ký hệ thống', 'Lịch sử thao tác và đăng nhập.',
        [['Sự kiện hôm nay', '412'], ['Cảnh báo', '3'], ['Đăng nhập thất bại', '7']],
        ['Thời gian', 'Người dùng', 'Hành động', 'Đối tượng', 'IP'],
        [['16/08 09:42', 'Nguyễn Ngọc Anh', 'Cập nhật giá', 'SF-1001', '113.161.x.x'],
         ['16/08 09:18', 'Phạm Đức Long', 'Duyệt phiếu nhập', 'PN-2608-04', '171.244.x.x'],
         ['16/08 08:56', 'Lê Thu Trang', 'Xuất bản bài viết', 'Xu hướng 2026', '14.161.x.x'],
         ['16/08 08:30', 'Vũ Mai Chi', 'Tạo coupon', 'SOFA10', '203.113.x.x'],
         ['16/08 08:02', 'Hệ thống', 'Đăng nhập thất bại', 'admin@sofa1.vn', '45.128.x.x']]),
    ],
  },
];

export const findSofa1AdminGroup = (slug?: string) =>
  SOFA1_ADMIN_GROUPS.find((g) => g.slug === slug);

export const findSofa1AdminSection = (groupSlug?: string, sectionSlug?: string) => {
  const group = findSofa1AdminGroup(groupSlug);
  if (!group) return undefined;
  return group.sections.find((x) => x.slug === sectionSlug);
};
