import { Iconify } from 'src/components/iconify';

export const sofa18PagesNavData = [
  { title: 'Trang chủ', path: '/sofa18', icon: <Iconify width={22} icon="solar:home-2-bold-duotone" /> },
  {
    title: 'Giới thiệu',
    path: '/sofa18/about',
    icon: <Iconify width={22} icon="solar:info-circle-bold-duotone" />,
    children: [
      { title: 'Giới thiệu công ty', path: '/sofa18/about' },
      { title: 'Lịch sử hình thành', path: '/sofa18/about/history' },
      { title: 'Tầm nhìn & Sứ mệnh', path: '/sofa18/about/vision' },
      { title: 'Giá trị cốt lõi', path: '/sofa18/about/values' },
      { title: 'Nhà máy sản xuất', path: '/sofa18/about/factory' },
      { title: 'Quy trình sản xuất', path: '/sofa18/about/process' },
      { title: 'Công nghệ sản xuất', path: '/sofa18/about/technology' },
      { title: 'Chứng nhận chất lượng', path: '/sofa18/about/certifications' },
      { title: 'Đội ngũ nhân sự', path: '/sofa18/about/team' },
      { title: 'Đối tác', path: '/sofa18/about/partners' },
      { title: 'Hình ảnh công ty', path: '/sofa18/about/gallery' },
      { title: 'Video giới thiệu', path: '/sofa18/about/video' },
    ],
  },
  {
    title: 'Sản phẩm',
    path: '/sofa18/products',
    icon: <Iconify width={22} icon="solar:armchair-bold-duotone" />,
    children: [
      { title: 'Tất cả sản phẩm', path: '/sofa18/products' },
      { title: 'Bộ sưu tập', path: '/sofa18/collections' },
      {
        title: 'Sofa phòng khách',
        path: '/sofa18/products/category/sofa-goc-chu-l',
        children: [
          { title: 'Sofa góc chữ L', path: '/sofa18/products/category/sofa-goc-chu-l' },
          { title: 'Sofa chữ U', path: '/sofa18/products/category/sofa-chu-u' },
          { title: 'Sofa văng', path: '/sofa18/products/category/sofa-vang' },
          { title: 'Sofa đơn', path: '/sofa18/products/category/sofa-don' },
          { title: 'Sofa băng dài', path: '/sofa18/products/category/sofa-bang-dai' },
          { title: 'Sofa giường', path: '/sofa18/products/category/sofa-giuong' },
          { title: 'Sofa thông minh', path: '/sofa18/products/category/sofa-thong-minh' },
          { title: 'Sofa thư giãn', path: '/sofa18/products/category/sofa-thu-gian' },
          { title: 'Sofa recliner', path: '/sofa18/products/category/sofa-recliner' },
          { title: 'Sofa da', path: '/sofa18/products/category/sofa-da' },
          { title: 'Sofa nỉ', path: '/sofa18/products/category/sofa-ni' },
          { title: 'Sofa vải', path: '/sofa18/products/category/sofa-vai' },
          { title: 'Sofa gỗ', path: '/sofa18/products/category/sofa-go' },
        ],
      },
      {
        title: 'Theo phong cách',
        path: '/sofa18/products/category/hien-dai',
        children: [
          { title: 'Hiện đại', path: '/sofa18/products/category/hien-dai' },
          { title: 'Tân cổ điển', path: '/sofa18/products/category/tan-co-dien' },
          { title: 'Bắc Âu', path: '/sofa18/products/category/bac-au' },
          { title: 'Luxury', path: '/sofa18/products/category/luxury' },
          { title: 'Minimalist', path: '/sofa18/products/category/minimalist' },
          { title: 'Indochine', path: '/sofa18/products/category/indochine' },
          { title: 'Châu Âu', path: '/sofa18/products/category/chau-au' },
        ],
      },
      {
        title: 'Theo không gian',
        path: '/sofa18/products/category/can-ho',
        children: [
          { title: 'Căn hộ', path: '/sofa18/products/category/can-ho' },
          { title: 'Nhà phố', path: '/sofa18/products/category/nha-pho' },
          { title: 'Biệt thự', path: '/sofa18/products/category/biet-thu' },
          { title: 'Văn phòng', path: '/sofa18/products/category/van-phong' },
          { title: 'Khách sạn', path: '/sofa18/products/category/khach-san' },
          { title: 'Resort', path: '/sofa18/products/category/resort' },
          { title: 'Nhà hàng', path: '/sofa18/products/category/nha-hang' },
          { title: 'Cafe', path: '/sofa18/products/category/cafe' },
        ],
      },
      {
        title: 'Theo kích thước',
        path: '/sofa18/products/category/sofa-nho',
        children: [
          { title: 'Sofa nhỏ', path: '/sofa18/products/category/sofa-nho' },
          { title: 'Sofa trung', path: '/sofa18/products/category/sofa-trung' },
          { title: 'Sofa lớn', path: '/sofa18/products/category/sofa-lon' },
        ],
      },
      {
        title: 'Theo giá',
        path: '/sofa18/products/category/duoi-10-trieu',
        children: [
          { title: 'Dưới 10 triệu', path: '/sofa18/products/category/duoi-10-trieu' },
          { title: '10-20 triệu', path: '/sofa18/products/category/10-20-trieu' },
          { title: '20-50 triệu', path: '/sofa18/products/category/20-50-trieu' },
          { title: 'Trên 50 triệu', path: '/sofa18/products/category/tren-50-trieu' },
        ],
      },
    ],
  },
  { title: 'Dự án', path: '/sofa18/projects', icon: <Iconify width={22} icon="solar:buildings-bold-duotone" /> },
  {
    title: 'Showroom',
    path: '/sofa18/showrooms',
    icon: <Iconify width={22} icon="solar:map-point-bold-duotone" />,
    children: [
      { title: 'Danh sách showroom', path: '/sofa18/showrooms' },
      { title: 'Đặt lịch tham quan', path: '/sofa18/showrooms/visit' },
      { title: 'Đặt lịch tư vấn', path: '/sofa18/showrooms/consult' },
    ],
  },
  {
    title: 'Dịch vụ',
    path: '/sofa18/services',
    icon: <Iconify width={22} icon="solar:tools-bold-duotone" />,
    children: [
      { title: 'Thiết kế nội thất', path: '/sofa18/services/design' },
      { title: 'Thiết kế sofa theo yêu cầu', path: '/sofa18/services/design/custom' },
      { title: 'Thiết kế 3D', path: '/sofa18/services/design/3d' },
      { title: 'Tư vấn bố trí nội thất', path: '/sofa18/services/design/consult' },
      { title: 'Dịch vụ sản xuất', path: '/sofa18/services/production' },
      { title: 'Gia công sofa', path: '/sofa18/services/production/crafting' },
      { title: 'Sofa OEM', path: '/sofa18/services/production/oem' },
      { title: 'Sofa ODM', path: '/sofa18/services/production/odm' },
      { title: 'Đặt hàng theo dự án', path: '/sofa18/services/production/project' },
    ],
  },
  { title: 'Blog', path: '/sofa18/blog', icon: <Iconify width={22} icon="solar:pen-bold-duotone" /> },
  {
    title: 'Khuyến mãi',
    path: '/sofa18/promotions',
    icon: <Iconify width={22} icon="solar:gift-bold-duotone" />,
    children: [
      { title: 'Bảo hành', path: '/sofa18/promotions/warranty' },
      { title: 'Bảo trì', path: '/sofa18/promotions/maintenance' },
      { title: 'Sửa chữa', path: '/sofa18/promotions/repair' },
      { title: 'Vệ sinh sofa', path: '/sofa18/promotions/cleaning' },
      { title: 'Đổi trả hàng', path: '/sofa18/promotions/returns' },
    ],
  },
  { title: 'Tuyển dụng', path: '/sofa18/careers', icon: <Iconify width={22} icon="solar:case-bold-duotone" /> },
  { title: 'Liên hệ', path: '/sofa18/contact', icon: <Iconify width={22} icon="solar:phone-bold-duotone" /> },
  {
    title: 'Tài khoản',
    path: '/sofa18/account',
    icon: <Iconify width={22} icon="solar:user-bold-duotone" />,
    children: [
      { title: 'Đăng nhập', path: '/sofa18/account/login' },
      { title: 'Đăng ký', path: '/sofa18/account/register' },
      { title: 'Quên mật khẩu', path: '/sofa18/account/forgot' },
      { title: 'Hồ sơ cá nhân', path: '/sofa18/account/profile' },
      { title: 'Đơn hàng của tôi', path: '/sofa18/account/orders' },
      { title: 'Địa chỉ giao hàng', path: '/sofa18/account/addresses' },
      { title: 'Yêu thích', path: '/sofa18/account/wishlist' },
      { title: 'Lịch sử giao dịch', path: '/sofa18/account/history' },
      { title: 'Phiếu bảo hành', path: '/sofa18/account/warranty' },
    ],
  },
  {
    title: 'Đại lý B2B',
    path: '/sofa18/b2b',
    icon: <Iconify width={22} icon="solar:hand-shake-bold-duotone" />,
    children: [
      { title: 'Giới thiệu hợp tác', path: '/sofa18/b2b' },
      { title: 'Đại lý phân phối', path: '/sofa18/b2b/distributor' },
      { title: 'Nhà phân phối', path: '/sofa18/b2b/wholesale' },
      { title: 'Đăng ký đại lý', path: '/sofa18/b2b/register' },
      { title: 'Đối tác thi công', path: '/sofa18/b2b/contractor' },
      { title: 'Báo giá dự án', path: '/sofa18/b2b/quote' },
      { title: 'Yêu cầu sản xuất OEM', path: '/sofa18/b2b/oem' },
      { title: 'Chính sách đại lý', path: '/sofa18/b2b/policy' },
    ],
  },
  {
    title: 'Mua hàng',
    path: '/sofa18/products',
    icon: <Iconify width={22} icon="solar:bag-bold-duotone" />,
    children: [
      { title: 'Danh sách sản phẩm', path: '/sofa18/products' },
      { title: 'Tìm kiếm sản phẩm', path: '/sofa18/search' },
      { title: 'So sánh sản phẩm', path: '/sofa18/compare' },
      { title: 'Thanh toán thành công', path: '/sofa18/checkout/success' },
      { title: 'Giỏ hàng', path: '/sofa18/cart' },
      { title: 'Thanh toán', path: '/sofa18/checkout' },
      { title: 'Theo dõi đơn hàng', path: '/sofa18/orders/tracking' },
      { title: 'Wishlist', path: '/sofa18/account/wishlist' },
    ],
  },
  {
    title: 'Hỗ trợ',
    path: '/sofa18/support',
    icon: <Iconify width={22} icon="solar:question-circle-bold-duotone" />,
    children: [
      { title: 'FAQ', path: '/sofa18/faq' },
      { title: 'Trung tâm trợ giúp', path: '/sofa18/support' },
      { title: 'Chat trực tuyến', path: '/sofa18/support/chat' },
      { title: 'Gửi ticket hỗ trợ', path: '/sofa18/support/ticket' },
      { title: 'Hướng dẫn mua hàng', path: '/sofa18/support/buying-guide' },
      { title: 'Hướng dẫn thanh toán', path: '/sofa18/support/payment-guide' },
      { title: 'Chính sách giao hàng', path: '/sofa18/policy/shipping' },
      { title: 'Chính sách bảo hành', path: '/sofa18/policy/warranty' },
      { title: 'Chính sách đổi trả', path: '/sofa18/policy/returns' },
    ],
  },
  {
    title: 'Khu vực thành viên',
    path: '/sofa18/member',
    icon: <Iconify width={22} icon="solar:users-group-rounded-bold-duotone" />,
    children: [
      { title: 'Dashboard khách hàng', path: '/sofa18/member/dashboard' },
      { title: 'Hồ sơ', path: '/sofa18/member/profile' },
      { title: 'Đơn hàng', path: '/sofa18/member/orders' },
      { title: 'Phiếu bảo hành', path: '/sofa18/member/warranty' },
      { title: 'Điểm tích lũy', path: '/sofa18/member/points' },
      { title: 'Voucher', path: '/sofa18/member/vouchers' },
      { title: 'Khiếu nại', path: '/sofa18/member/complaints' },
      { title: 'Dashboard đại lý', path: '/sofa18/member/dealer' },
      { title: 'Chính sách giá', path: '/sofa18/member/dealer-pricing' },
      { title: 'Báo giá', path: '/sofa18/member/dealer-quotes' },
      { title: 'Đơn hàng đại lý', path: '/sofa18/member/dealer-orders' },
      { title: 'Công nợ', path: '/sofa18/member/dealer-debt' },
      { title: 'Tài liệu bán hàng', path: '/sofa18/member/dealer-docs' },
    ],
  },
];
