import { Iconify } from 'src/components/iconify';

export const sofa3PagesNavData = [
  { title: 'Trang chủ', path: '/sofa3', icon: <Iconify width={22} icon="solar:home-2-bold-duotone" /> },
  {
    title: 'Giới thiệu',
    path: '/sofa3/about',
    icon: <Iconify width={22} icon="solar:info-circle-bold-duotone" />,
    children: [
      { title: 'Giới thiệu công ty', path: '/sofa3/about' },
      { title: 'Lịch sử hình thành', path: '/sofa3/about/history' },
      { title: 'Tầm nhìn & Sứ mệnh', path: '/sofa3/about/vision' },
      { title: 'Giá trị cốt lõi', path: '/sofa3/about/values' },
      { title: 'Nhà máy sản xuất', path: '/sofa3/about/factory' },
      { title: 'Quy trình sản xuất', path: '/sofa3/about/process' },
      { title: 'Công nghệ sản xuất', path: '/sofa3/about/technology' },
      { title: 'Chứng nhận chất lượng', path: '/sofa3/about/certifications' },
      { title: 'Đội ngũ nhân sự', path: '/sofa3/about/team' },
      { title: 'Đối tác', path: '/sofa3/about/partners' },
      { title: 'Hình ảnh công ty', path: '/sofa3/about/gallery' },
      { title: 'Video giới thiệu', path: '/sofa3/about/video' },
    ],
  },
  {
    title: 'Sản phẩm',
    path: '/sofa3/products',
    icon: <Iconify width={22} icon="solar:armchair-bold-duotone" />,
    children: [
      { title: 'Tất cả sản phẩm', path: '/sofa3/products' },
      { title: 'Bộ sưu tập', path: '/sofa3/collections' },
      {
        title: 'Sofa phòng khách',
        path: '/sofa3/products/category/sofa-goc-chu-l',
        children: [
          { title: 'Sofa góc chữ L', path: '/sofa3/products/category/sofa-goc-chu-l' },
          { title: 'Sofa chữ U', path: '/sofa3/products/category/sofa-chu-u' },
          { title: 'Sofa văng', path: '/sofa3/products/category/sofa-vang' },
          { title: 'Sofa đơn', path: '/sofa3/products/category/sofa-don' },
          { title: 'Sofa băng dài', path: '/sofa3/products/category/sofa-bang-dai' },
          { title: 'Sofa giường', path: '/sofa3/products/category/sofa-giuong' },
          { title: 'Sofa thông minh', path: '/sofa3/products/category/sofa-thong-minh' },
          { title: 'Sofa thư giãn', path: '/sofa3/products/category/sofa-thu-gian' },
          { title: 'Sofa recliner', path: '/sofa3/products/category/sofa-recliner' },
          { title: 'Sofa da', path: '/sofa3/products/category/sofa-da' },
          { title: 'Sofa nỉ', path: '/sofa3/products/category/sofa-ni' },
          { title: 'Sofa vải', path: '/sofa3/products/category/sofa-vai' },
          { title: 'Sofa gỗ', path: '/sofa3/products/category/sofa-go' },
        ],
      },
      {
        title: 'Theo phong cách',
        path: '/sofa3/products/category/hien-dai',
        children: [
          { title: 'Hiện đại', path: '/sofa3/products/category/hien-dai' },
          { title: 'Tân cổ điển', path: '/sofa3/products/category/tan-co-dien' },
          { title: 'Bắc Âu', path: '/sofa3/products/category/bac-au' },
          { title: 'Luxury', path: '/sofa3/products/category/luxury' },
          { title: 'Minimalist', path: '/sofa3/products/category/minimalist' },
          { title: 'Indochine', path: '/sofa3/products/category/indochine' },
          { title: 'Châu Âu', path: '/sofa3/products/category/chau-au' },
        ],
      },
      {
        title: 'Theo không gian',
        path: '/sofa3/products/category/can-ho',
        children: [
          { title: 'Căn hộ', path: '/sofa3/products/category/can-ho' },
          { title: 'Nhà phố', path: '/sofa3/products/category/nha-pho' },
          { title: 'Biệt thự', path: '/sofa3/products/category/biet-thu' },
          { title: 'Văn phòng', path: '/sofa3/products/category/van-phong' },
          { title: 'Khách sạn', path: '/sofa3/products/category/khach-san' },
          { title: 'Resort', path: '/sofa3/products/category/resort' },
          { title: 'Nhà hàng', path: '/sofa3/products/category/nha-hang' },
          { title: 'Cafe', path: '/sofa3/products/category/cafe' },
        ],
      },
      {
        title: 'Theo kích thước',
        path: '/sofa3/products/category/sofa-nho',
        children: [
          { title: 'Sofa nhỏ', path: '/sofa3/products/category/sofa-nho' },
          { title: 'Sofa trung', path: '/sofa3/products/category/sofa-trung' },
          { title: 'Sofa lớn', path: '/sofa3/products/category/sofa-lon' },
        ],
      },
      {
        title: 'Theo giá',
        path: '/sofa3/products/category/duoi-10-trieu',
        children: [
          { title: 'Dưới 10 triệu', path: '/sofa3/products/category/duoi-10-trieu' },
          { title: '10-20 triệu', path: '/sofa3/products/category/10-20-trieu' },
          { title: '20-50 triệu', path: '/sofa3/products/category/20-50-trieu' },
          { title: 'Trên 50 triệu', path: '/sofa3/products/category/tren-50-trieu' },
        ],
      },
    ],
  },
  { title: 'Dự án', path: '/sofa3/projects', icon: <Iconify width={22} icon="solar:buildings-bold-duotone" /> },
  {
    title: 'Showroom',
    path: '/sofa3/showrooms',
    icon: <Iconify width={22} icon="solar:map-point-bold-duotone" />,
    children: [
      { title: 'Danh sách showroom', path: '/sofa3/showrooms' },
      { title: 'Đặt lịch tham quan', path: '/sofa3/showrooms/visit' },
      { title: 'Đặt lịch tư vấn', path: '/sofa3/showrooms/consult' },
    ],
  },
  {
    title: 'Dịch vụ',
    path: '/sofa3/services',
    icon: <Iconify width={22} icon="solar:tools-bold-duotone" />,
    children: [
      { title: 'Thiết kế nội thất', path: '/sofa3/services/design' },
      { title: 'Thiết kế sofa theo yêu cầu', path: '/sofa3/services/design/custom' },
      { title: 'Thiết kế 3D', path: '/sofa3/services/design/3d' },
      { title: 'Tư vấn bố trí nội thất', path: '/sofa3/services/design/consult' },
      { title: 'Dịch vụ sản xuất', path: '/sofa3/services/production' },
      { title: 'Sofa OEM', path: '/sofa3/services/production/oem' },
      { title: 'Sofa ODM', path: '/sofa3/services/production/odm' },
      { title: 'Đặt hàng theo dự án', path: '/sofa3/services/production/project' },
    ],
  },
  { title: 'Blog', path: '/sofa3/blog', icon: <Iconify width={22} icon="solar:pen-bold-duotone" /> },
  {
    title: 'Khuyến mãi',
    path: '/sofa3/promotions',
    icon: <Iconify width={22} icon="solar:gift-bold-duotone" />,
    children: [
      { title: 'Bảo hành', path: '/sofa3/promotions/warranty' },
      { title: 'Bảo trì', path: '/sofa3/promotions/maintenance' },
      { title: 'Sửa chữa', path: '/sofa3/promotions/repair' },
      { title: 'Vệ sinh sofa', path: '/sofa3/promotions/cleaning' },
      { title: 'Đổi trả hàng', path: '/sofa3/promotions/returns' },
    ],
  },
  { title: 'Tuyển dụng', path: '/sofa3/careers', icon: <Iconify width={22} icon="solar:case-bold-duotone" /> },
  { title: 'Liên hệ', path: '/sofa3/contact', icon: <Iconify width={22} icon="solar:phone-bold-duotone" /> },
  { title: 'Tài khoản', path: '/sofa3/account', icon: <Iconify width={22} icon="solar:user-bold-duotone" /> },
  {
    title: 'Đại lý B2B',
    path: '/sofa3/b2b',
    icon: <Iconify width={22} icon="solar:hand-shake-bold-duotone" />,
    children: [
      { title: 'Giới thiệu hợp tác', path: '/sofa3/b2b' },
      { title: 'Đăng ký đại lý', path: '/sofa3/b2b/register' },
      { title: 'Báo giá dự án', path: '/sofa3/b2b/quote' },
      { title: 'Yêu cầu sản xuất OEM', path: '/sofa3/b2b/oem' },
      { title: 'Chính sách đại lý', path: '/sofa3/b2b/policy' },
    ],
  },
  { title: 'Giỏ hàng', path: '/sofa3/cart', icon: <Iconify width={22} icon="solar:cart-bold-duotone" /> },
  { title: 'Thanh toán', path: '/sofa3/payment', icon: <Iconify width={22} icon="solar:wallet-bold-duotone" /> },
  { title: 'Hỗ trợ', path: '/sofa3/support', icon: <Iconify width={22} icon="solar:question-circle-bold-duotone" /> },
  {
    title: 'Quản trị',
    path: '/sofa3/admin',
    icon: <Iconify width={22} icon="solar:widget-5-bold-duotone" />,
    children: [
      { title: 'Tổng quan', path: '/sofa3/admin' },
      { title: 'CMS', path: '/sofa3/admin/cms' },
      { title: 'Sản phẩm', path: '/sofa3/admin/catalog' },
      { title: 'Kho hàng', path: '/sofa3/admin/warehouse' },
      { title: 'Đơn hàng', path: '/sofa3/admin/orders' },
      { title: 'CRM', path: '/sofa3/admin/crm' },
      { title: 'Marketing', path: '/sofa3/admin/marketing' },
      { title: 'Analytics', path: '/sofa3/admin/analytics' },
      { title: 'SEO', path: '/sofa3/admin/seo' },
      { title: 'Phân quyền', path: '/sofa3/admin/access' },
    ],
  },
];
